### ISSUE TITLE
Create sidebar (or other elements persistent on all pages)

### ISSUE THREAD

**Issue by olahesoo** [tarkvaraprojekt-2019/Tarkvaraprojekt#10]
- [x] Logout button
- [x] Victim management button
- [ ] Change password button (for non-administrators)
- [x] Account management button (for administrators)
- [x] Create report button (for administrators)
- [x] Backup management button (for administrators)

Time estimation: 16 hours

[Requirements 2, 3](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements), [Use Case UC-1](https://github.com/TornOne/Tarkvaraprojekt/wiki/Detailed-Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 1](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)

**Comment by KingBoomie** [comment]
Change password button depending on #85
