### ISSUE TITLE
Backend login authentication

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#21]
- [x] Server can receive login attempts
- [x] Server sends back a confirmation
- [x] Server sends back a failed login notice for an incorrect user/pass combination

Time estimation: 10 hrs
[Requirement 1](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 21](https://github.com/TornOne/Tarkvaraprojekt/wiki/Nonfunctional-Requirements)
