### ISSUE TITLE
Input existing data into databases

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#25]
- [ ] Split the data to victim data and incident data
- [ ] Remove errors from the data
- [ ] Insert the data into the database tables

Time estimate: 8h

[Requirement 15](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 11](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)
