### ISSUE TITLE
Backend victim info retrieval

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#26]
- [x] Validate the user
- [x] Send back the victim's information and all incidents
- [x] Send back a not authorized
- [ ] Send back a victim not found

Time estimation: 15 hrs
[Requirement 7](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements), [Use Case UC-2](https://github.com/TornOne/Tarkvaraprojekt/wiki/Detailed-Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 9](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)
