### ISSUE TITLE
Frontend victim info page

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#27]
- [x] Send request to server to get victim info by ID
- [x] Receive response
- [x] Display existing victim info with the possibility to edit
- [x] Display list of incidents (click to view and edit)
- [x] Add new incident button

Time estimation: 16 hours

[Requirement 7](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements), [Use Case UC-2](https://github.com/TornOne/Tarkvaraprojekt/wiki/Detailed-Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 19](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)
