### ISSUE TITLE
Victim creation screen

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#28]
- [x] Have all the right input fields
- [x] Fill in some of the fields if editing an existing victim or if coming from the victim search screen
- [ ] Check all input fields in realtime (before submitting) for errors
- [x] Send victim data to server and direct back to victim info page

Time estimation: 16 hours

[Requirements 9, 11](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 12](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)
