### ISSUE TITLE
Backend victim info saving

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#29]
- [ ] Validate the user
- [ ] Validate data correctness
- [ ] Save or overwrite victim info
- [ ] Send back confirmation / error

Time estimation: 15 hrs

[Requirements 9, 11](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 12](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)
