### ISSUE TITLE
Incident creation screen

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#30]
- [x] Have all the right input fields
- [x] Also have repeating info fields
- [x] Fill in the fields if editing an existing case
- [ ] Check all input fields in realtime (before submitting) for errors
- [x] Send incident data to server and direct back to victim info page (only send new or modified rows)

Time estimation: 16 hours

[Requirements 10, 12](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 13](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)
