### ISSUE TITLE
Add back buttons to pages

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#31]
- [x] Add a back button to all pages where it makes sense
- [x] Make the back button synonymous with the browser back button

Estimated time: 4 hours.

**Comment by olahesoo** [comment]
[Requirement 32](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)

**Comment by KingBoomie** [comment]
closed with bcecd05
