### ISSUE TITLE
Backend incident saving

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#32]
- [x] Validate the user
- [x] Validate data correctness
- [x] Save or overwrite incident info
- [x] Send back confirmation / error

Time estimation: 15 hrs
[Requirements 10, 12](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)

**Comment by olahesoo** [comment]
[Requirement 17](https://github.com/TornOne/Tarkvaraprojekt/wiki/Functional-Requirements)
