### ISSUE TITLE
Manual deletion of victims

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#46]
- [ ] ~~A button that purges all clients without any identifying information (only their id). (These victims in theory have no way to be found and clutter the system.)~~ (Not doing this?)
- [ ] An id field and a button that deletes this one person.
In both cases, all incidents and sessions will delete too.

**Comment by KingBoomie** [comment]
Should perhaps this functionality be restricted only to administrators?

**Comment by TornOne** [comment]
Yes
