### ISSUE TITLE
Log out button does nothing

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#84]
Should
- [x] Remove auth token locally
- [x] Direct to login page
- [x] Send a log out message to back-end (OPTIONAL, needs discussing?)

**Comment by KingBoomie** [comment]
Fixed first two points with 36ac5cf856b4192e3d3833989ed533cf3b785a2a. 
I can send a log out message to the back-end should someone there make a suitable end-point for that. I assume it's for resetting the auth token and it's probably a good idea to do that.
