### ISSUE TITLE
Sidebar does not differentiate between admin and normal users

### ISSUE THREAD

**Issue by TornOne** [tarkvaraprojekt-2019/Tarkvaraprojekt#85]
Admins should have "Varundus", "Aruandlus", and "Kasutajad".  
Regular users should have "Muuda parooli".  
Everyone should have "Ülevaade".

**Comment by KingBoomie** [comment]
Can't do "Muuda parooli", since there is no endpoint for changing the password for non admin users. 
@TornOne
